# This is a basic workflow to help you get started with Actions

name: CI-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: "*" # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc-13 g++-13 libopencv-dev

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=ON -S Lecture_10/ -B ${{github.workspace}}/cmake-build-release

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-release

      - name: Run Google Tests
        run: ${{github.workspace}}/cmake-build-release/tests/runGTests

      - name: Run DocTests
        run: ${{github.workspace}}/cmake-build-release/tests/runDocTests